/*
 * UART_Cfg.h
 *
 *  Created on: Jan 21, 2023
 *      Author: abdelrahmanhossam
 */

#ifndef INCLUDE_MCAL_UART_UART_CFG_H_
#define INCLUDE_MCAL_UART_UART_CFG_H_


#define F_CPU    8000000UL
#define BAUDRATE 9600

#define TX_INTERRUPT_ENABLE					INTERRUPT_DISABLE
#define RX_INTERRUPT_ENABLE					INTERRUPT_DISABLE
#define DATA_REG_EMPTY_INTERRUPT_ENABLE		INTERRUPT_DISABLE

#define CHARACTER_SIZE	EIGHT_BITS

#define MODE_OF_OPERATION	ASYNCHRONOUS

#define PARITY_MODE	P_DISABLED

#define STOP_BITS	ONE_STOP_BIT

#define SPEED_MODE	NORMAL_SPEED

#define NON_BLOCKING_TIME_OUT 5000

#define RETURN_NO_RECEIVED_DATA 255

#endif /* INCLUDE_MCAL_UART_UART_CFG_H_ */
