/*
 * LCD_Private.h
 *
 *  Created on: Dec 3, 2022
 *      Author: abdelrahmanhossam
 */

#ifndef INCLUDE_HAL_LCD_LCD_PRIVATE_H_
#define INCLUDE_HAL_LCD_LCD_PRIVATE_H_

#define E_DELAY	2
#define INIT_VDD_DELAY 32

#define DONT_CARE_BIT	0

#define FUNCTION_SET CONC_BIT(0,0,1,1,NO_OF_LINES,CHARACTER_FONT,DONT_CARE_BIT,DONT_CARE_BIT)

#define DISPLAY_ON_OFF_CONTROL CONC_BIT(0,0,0,0,1,DISPLAY_STATUS,CURSOR_DISPLAY,CURSOR_BLINK)

#define DISPLAY_CLEAR 0x01

#define ENTRY_MODE_SET CONC_BIT(0,0,0,0,0,1,I_D,SHIFT)

#define LCD_ROW_1_ADDRESS	127
#define LCD_ROW_2_ADDRESS	191

#endif /* INCLUDE_HAL_LCD_LCD_PRIVATE_H_ */
